services:
  directus:
    extends:
      file: ./backend/compose.yml
      service: directus
    container_name: directus
    ports:
      - "127.0.0.1:8055:8055"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "cat /proc/1/cmdline | grep 'ecosystem.config.cjs' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - intranet

  website:
    build:
      context: ./lochwinnoch-website
      dockerfile: Dockerfile.website
    container_name: "website"
    environment:
      - HOST=0.0.0.0
      - PORT=4321
      - DEMO_USER=${DEMO_USER}
      - DEMO_PASSWORD=${DEMO_PASSWORD}
      - DIRECTUS_URL=${DIRECTUS_URL}
      - WEB3FORMS_ACCESS_KEY=${WEB3FORMS_ACCESS_KEY}
    ports:
      - "127.0.0.1:4321:4321"
    depends_on:
      directus:
        condition: service_started

    networks:
      - intranet

networks:
  intranet:
    driver: bridge
