#!/bin/ash
set -e

CYAN="\\033[36m"
BLUE="\\033[34m"
RESET="\\033[0m"

echo -e "${CYAN}[$(date +'%d-%b-%Y %H:%M:%S')] App service init script called.${RESET}"

echo -e "${CYAN}[$(date +'%d-%b-%Y %H:%M:%S')] Waiting for the cms to come online...${RESET}"
while ! getent hosts directus; do
    echo -e "${CYAN}[$(date +'%d-%M-%Y %H:%M:%S')] Waiting for the cms to come online...${RESET}"
    sleep 5
done

echo -e "${CYAN}[$(date +'%d-%b-%Y %H:%M:%S')] Cms service is online.${RESET}"
echo -e "${CYAN}[$(date +'%d-%b-%Y %H:%M:%S')] Starting up the application in due order...${RESET}"


echo -e "${CYAN}[$(date +'%d-%b-%Y %H:%M:%S')] STARTING ${BLUE}SERVER${CYAN} NOW. OFF TO THE RACES!${RESET}"

exec "$@"
