# SRC:
# https://dev.to/code42cate/how-to-dockerize-and-deploy-astro-6ll 

FROM node:22.14.0-alpine as base

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm i

COPY . .


# Build the Astro project
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321
CMD ["node", "./dist/server/entry.mjs"]
